"""Regenerate the release report and aggregate tables from all saved sample metrics."""
from pathlib import Path
import csv,json,html
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
ROOT=Path(__file__).resolve().parents[1]
METRICS=['ca_rmsd','tm_score','ca_lddt','avg_plddt','ptm']
def main():
 m=json.loads((ROOT/'manifest.json').read_text());rows=list(csv.DictReader((ROOT/'results/per_sample.csv').open()));summary=[]
 for key,c in m['conditions'].items():
  rr=[r for r in rows if r['protein']==c['protein'] and r['arm']==c['arm']]
  summary.append(dict(protein=c['protein'],arm=c['arm'],category=c['category'],samples=len(rr),**{k:float(np.mean([float(r[k]) for r in rr])) for k in METRICS}))
 with (ROOT/'results/summary.csv').open('w') as f:w=csv.DictWriter(f,fieldnames=list(summary[0]));w.writeheader();w.writerows(summary)
 lookup={(s['protein'],s['arm']):s for s in summary};names=['dhfr','thioredoxin','cyclophilin','ubiquitin','myoglobin','lysozyme','ci2','top7','acylphosphatase','antifreeze']
 arms=['no_msa','query_only','natural_all','synthetic_40','synthetic_60'];labels=['No MSA','Query only','Natural/search MSA','Synthetic 40%','Synthetic 60%']
 colors=['#aaa','#444','#128566','#397cc4','#e39b20'];fig,ax=plt.subplots(figsize=(15,5))
 for j,(arm,label,color) in enumerate(zip(arms,labels,colors)):
  for i,n in enumerate(names):
   if (n,arm) not in lookup:continue
   x=i+(j-2)*.14;v=[float(r['tm_score']) for r in rows if r['protein']==n and r['arm']==arm];ax.plot(x,np.mean(v),'o',color=color,label=label if i==next(k for k,z in enumerate(names) if (z,arm) in lookup) else None);ax.vlines(x,min(v),max(v),color=color,alpha=.4)
 ax.set_xticks(range(10),names,rotation=25,ha='right');ax.set_ylabel('TM-score to deposited reference');ax.set_ylim(0,1.03);ax.grid(axis='y',alpha=.2);ax.legend(ncol=5,fontsize=9,loc='lower left');fig.tight_layout();fig.savefig(ROOT/'results/comparison.png',dpi=170);plt.close(fig)
 wins=sum(lookup[n,'synthetic_40']['tm_score']>lookup[n,'no_msa']['tm_score'] for n in names);assert wins==9
 h=['<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DPLM synthetic MSA benchmark</title><style>body{font:16px system-ui;color:#182738;max-width:1450px;margin:40px auto;padding:20px;line-height:1.5}table{border-collapse:collapse;width:100%}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}img{max-width:100%}a{color:#166c9a}.note{background:#eef4f8;padding:16px}</style>', '<h1>DPLM synthetic MSAs: ten-protein OpenFold-3 benchmark</h1><p>Release candidate v0.1.0 · 6 October 2026</p>', '<p class="note"><strong>Observed result:</strong> 50 unconstrained DPLM variants at 40% masking improve mean TM-score over no MSA in 9 of 10 proteins. Same query, OpenFold checkpoint, model seed and sample count across conditions. This is a measured input effect; evolutionary covariation, variant function and generalization to unseen proteins are not established by this experiment.</p>', '<p>305 predictions are included once: 275 in the main comparison, 15 in the 250-variant depth extension, and 15 from superseded constrained trials. Each condition has five diffusion samples from one model seed. Query-only controls are available for the seven newer proteins. All structures, confidence files, MSAs, accepted variant pools and generation audits are included.</p><p><a href="README.txt">Setup and runnable examples</a> · <a href="manifest.json">Manifest</a> · <a href="results/per_sample.csv">All sample metrics</a> · <a href="results/summary.csv">All condition means</a> · <a href="THIRD_PARTY_NOTICES.txt">Attribution</a> · <a href="LICENSE">MIT license</a></p><img src="results/comparison.png" alt="Ten protein TM-score comparison; dots are condition means, lines are five-sample ranges."><h2>Main comparison: mean TM-score</h2><table><tr><th>Protein / PDB</th><th>Retrieved hits</th>'+''.join(f'<th>{x}</th>' for x in labels)+'</tr>']
 for n in names:
  p=m['proteins'][n];h.append(f'<tr><td>{n} / <a href="https://www.rcsb.org/structure/{p["reference"]}">{p["reference"]}</a></td><td>{p["natural_depth"]:,}</td>'+''.join(f'<td>{lookup[n,a]["tm_score"]:.3f}</td>' if (n,a) in lookup else '<td>Not run</td>' for a in arms)+'</tr>')
 h+=['</table><p>Top7 is a designed protein; its four search hits are not verified natural homologs. Natural depth counts distinct aligned nonquery rows, not independent evolutionary observations. The MSA embedder uses at most 1024 rows; the sequence profile is calculated before that subsampling.</p><h2>What changes with masking?</h2><p>Higher masking is protein-dependent. In the shallow antifreeze case, query-only TM-score is 0.243, 40% synthetic masking reaches 0.726, and 60% masking falls to 0.198; the natural MSA reaches 0.957. Myoglobin, CI2 and acylphosphatase approach natural-MSA accuracy with synthetic input. Ubiquitin and Top7 already fold well without additional sequences.</p><h2>Interpretation and protocol</h2><ul><li>Main generation: original Gumbel sampler; no temperature increase, permanently protected residues, identity filtering, adaptive masking or fold-score selection. First 50 unique canonical query-length variants; query copies excluded. Unmasked random positions supply query context per candidate.</li><li>OpenFold-3 0.4.0, checkpoint of3-p2-155k; model seed 2746317213, five samples, no templates or ligands. Every arm predicts the same query sequence; generated variants are MSA rows.</li><li>No-MSA flags produce a gap row and zero profile in this version. Query-only preserves query-derived MSA features. These are distinct baselines; no neural-network layers are removed.</li><li>Ten short, structurally characterized proteins constitute a convenience sample. Model training overlap is possible; five correlated samples are not independent replicate experiments. No random-mutation control or experimental functional validation was performed.</li><li>RMSD is whole-chain Cα Kabsch RMSD, TM-score uses TM-align normalized by reference length, and lDDT here uses Cα distances. Confidence is a model output, not experimental accuracy.</li></ul><h2>Reference details</h2><ul>']
 for n in names:h.append(f'<li><strong>{n}:</strong> {html.escape(m["proteins"][n]["notes"])}</li>')
 h+=['</ul><h2>Every condition and structure</h2><p>Exploratory conditions are explicitly labeled and excluded from the 9/10 headline. Their exact residue constraints and sampling settings are preserved in generation metadata. They include the earlier temperature-3 cyclophilin trial.</p><table><tr><th>Protein</th><th>Condition</th><th>Category</th><th>RMSD Å</th><th>TM</th><th>Cα lDDT</th><th>pLDDT</th><th>pTM</th><th>Five CIFs</th></tr>']
 for s in summary:
  rr=[r for r in rows if r['protein']==s['protein'] and r['arm']==s['arm']];links=' '.join(f'<a href="{r["file"]}">{r["sample"]}</a>' for r in rr)
  h.append(f'<tr><td>{s["protein"]}</td><td>{s["arm"]}</td><td>{s["category"]}</td>'+''.join(f'<td>{s[k]:.3f}</td>' for k in METRICS)+f'<td>{links}</td></tr>')
 h+=['</table><p>Raw data, reference sequences and metadata are indexed by <a href="manifest.json">manifest.json</a>. No model weights, credentials or cloud account identifiers are included.</p></html>']
 (ROOT/'index.html').write_text('\n'.join(h));print(f'{len(summary)} condition summaries; {wins}/10 improve at 40% masking.')
if __name__=='__main__':main()
